package com.devdad.Forma.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "users") // Match PostgreSQL DB.
public class User {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	private String firstName;
	private String lastName;
	private String profilePicture;
	private String googleId;
	private String provider;

	@Column(unique = true, nullable = false)
	private String email;

	@Column(nullable = false)
	private String password;

	// Default to USER role.
	private String role = UserRole.USER.toString();

	// Allows for us to save the wishlist automatically when a new User is saved.
	@OneToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	// FK column in the User table pointing to Wishlist
	@JoinColumn(name = "wishlist_id")
	// Exclude this from the .toString() generated by Lombok to stop circular
	// dependecy issue
	@ToString.Exclude
	// @JsonIgnoreProperties("user") // Prevent recursion: when serializing
	// Wishlist, skip its user field
	private Wishlist wishlist;

	// Handle edge cases where if the Wishlist gets saved outside of the main
	// service, we ensure users have a wishlist.
	@PrePersist
	public void PrePersist() {
		if (this.wishlist == null) {
			Wishlist wishlist = new Wishlist();
			wishlist.setUser(this);
			this.wishlist = wishlist;
		}
	}
}
